### ISSUE TITLE
mipsel-linux-musl: error: 'EX_IOERR' was not declared in this scope

### ISSUE THREAD

**Issue by nalzok** [ziglang/zig-bootstrap#67] opened 2021-09-09 12:13 UTC
Hi there, I got the following error when bootstrapping for a `mipsel-linux-musl` target on a macOS 10.14 host.

```
$ ./build -j1 mipsel-linux-musl 1004kc
-- The ASM compiler identification is unknown
-- Found assembler: /opt/local/bin/zig
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Warning: Did not find file Compiler/-ASM
-- clang project is enabled
-- clang-tools-extra project is disabled
-- compiler-rt project is disabled
-- debuginfo-tests project is disabled
-- libc project is disabled
-- libclc project is disabled
-- libcxx project is disabled
-- libcxxabi project is disabled
-- libunwind project is disabled
-- lld project is enabled
-- lldb project is disabled
-- mlir project is disabled
-- openmp project is disabled
-- parallel-libs project is disabled
-- polly project is disabled
-- pstl project is disabled
-- flang project is disabled
-- Found libtool - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Could NOT find Backtrace (missing: Backtrace_LIBRARY)
-- Native target architecture is X86
-- Threads disabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Found ld64 - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH)
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-apple-darwin18.7.0
-- LLVM default target triple: x86_64-apple-darwin18.7.0
CMake Warning at cmake/modules/HandleLLVMOptions.cmake:261 (message):
  -fPIC is not supported.
Call Stack (most recent call first):
  cmake/modules/HandleLLVMOptions.cmake:297 (add_flag_or_print_warning)
  CMakeLists.txt:698 (include)


-- Targeting AArch64
-- Targeting AMDGPU
-- Targeting ARM
-- Targeting AVR
-- Targeting BPF
-- Targeting Hexagon
-- Targeting Lanai
-- Targeting Mips
-- Targeting MSP430
-- Targeting NVPTX
-- Targeting PowerPC
-- Targeting RISCV
-- Targeting Sparc
-- Targeting SystemZ
-- Targeting WebAssembly
-- Targeting X86
-- Targeting XCore
-- Clang version: 12.0.1
-- Host linker version: 530
-- Performing Test LINKER_ORDER_FILE_WORKS
-- Performing Test LINKER_ORDER_FILE_WORKS - Success
-- LLD version: 12.0.1
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/zig-bootstrap/out/build-llvm-host
Consolidate compiler generated dependencies of target LLVMDemangle
[  0%] Built target LLVMDemangle
Scanning dependencies of target LLVMSupport
Consolidate compiler generated dependencies of target LLVMSupport
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/CrashRecoveryContext.cpp.o
In file included from /tmp/zig-bootstrap/llvm/lib/Support/CrashRecoveryContext.cpp:12:0:
/tmp/zig-bootstrap/llvm/include/llvm/Support/ExitCodes.h:30:2: error: #error Exit code EX_IOERR not available
 #error Exit code EX_IOERR not available
  ^~~~~
/tmp/zig-bootstrap/llvm/lib/Support/CrashRecoveryContext.cpp: In function 'void CrashRecoverySignalHandler(int)':
/tmp/zig-bootstrap/llvm/lib/Support/CrashRecoveryContext.cpp:385:15: error: 'EX_IOERR' was not declared in this scope
     RetCode = EX_IOERR;
               ^~~~~~~~
/tmp/zig-bootstrap/llvm/lib/Support/CrashRecoveryContext.cpp:385:15: note: suggested alternative: 'EDEVERR'
     RetCode = EX_IOERR;
               ^~~~~~~~
               EDEVERR
make[2]: *** [lib/Support/CMakeFiles/LLVMSupport.dir/CrashRecoveryContext.cpp.o] Error 1
make[1]: *** [lib/Support/CMakeFiles/LLVMSupport.dir/all] Error 2
make: *** [all] Error 2
```

Here is some system information you may find helpful

```
$ zig version
0.8.0
$ zig env
{
 "zig_exe": "/opt/local/bin/zig",
 "lib_dir": "/opt/local/lib/zig",
 "std_dir": "/opt/local/lib/zig/std",
 "global_cache_dir": "/Users/nalzok/.cache/zig",
 "version": "0.8.0"
}
$ zig libc
Zig attempted to find the path to native system libc headers by executing this command:
zig cc -target mips64-linux-musl -E -Wp,-v -xc /dev/null
error: unable to detect native libc: UnableToSpawnCCompiler
```

Could you please take a look?

**Comment by andrewrk** [comment] 2021-11-22 03:01
Duplicate of  #12

**Closed by andrewrk** 2021-11-22 03:01 UTC
